# Generated by Django 3.2.25 on 2024-05-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_auto_20240425_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenton',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
